bcrypt:
  salto: 10
  secretKey: mySecretKey
database:
  pg:
    host: 'localhost'
    user: 'postgres'
    port: 5432
    password: 'sa'
    database: 'turismodiasdb'
    max: 20
    idleTimeoutMillis: 30000
    connectionTimeoutMillis: 2000
  typeorm:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    username: 'postgres'
    password: 'sa'
    database: 'turismodiazdb'
    logging: true
    synchronize: false
jwt:
  secretKey: turismoDiaz
  expiresIn: 24h

